name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image to ECR
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Configure AWS Credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    # Step 3: Login to Amazon ECR
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    # Step 4: Build and Tag the Docker Image
    - name: Build Docker Image
      run: |
        IMAGE_TAG=latest
        IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/spring-boot-app-repo:$IMAGE_TAG
        docker build -t $IMAGE_URI .
        echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

    # Step 5: Push Docker Image to ECR
    - name: Push Docker Image
      run: |
        docker push ${{ env.IMAGE_URI }}
